import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/componentes/shared/Footer";

export const metadata: Metadata = {
    title: "Zbank",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: '/favicon.svg', media: '(prefers-color-scheme: light)' },
            { url: '/faviconDarkMode.svg', media: '(prefers-color-scheme: dark)' },
        ],
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="pt-BR">
            <body className="min-h-screen">
                {children}
                <Footer />
            </body>
        </html>
    );
}